packages:
- name: server
  type: go
  deps:
  - pkg/webui:rice
  - pkg/store/postgres:rice
  srcs:
  - "**/*.go"
  - "go.mod"
  - "go.sum"
  env:
  - CGO_ENABLED=0
  config:
    generate: true
    dontTest: true
    buildFlags:
    - -tags
    - server
- name: plugin-client-lib
  type: go
  config:
    packaging: library
  srcs:
  - "pkg/plugin/client/*.go"
  - "pkg/plugin/common/*.go"
  - "pkg/filterexpr/*.go"
  - "pkg/api/**/*.go"
  - "go.mod"
  - "go.sum"
- name: server-docker
  type: docker
  deps:
  - :server
  - integrations/plugins/webhook:app
  config:
    dockerfile: "server.Dockerfile"
- name: client
  type: go
  srcs:
  - "**/*.go"
  - "go.mod"
  - "go.sum"
  env:
  - CGO_ENABLED=0
  config:
    dontTest: true
    buildFlags:
    - -tags
    - client
- name: all
  type: generic
  deps:
  - :client
  - :server