apiVersion: v1
kind: Secret
metadata:
  name: {{ include "werft.fullname" . }}-github
  labels:
    app.kubernetes.io/name: {{ include "werft.name" . }}
    helm.sh/chart: {{ include "werft.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    checksum/checksd-config: {{ .Files.Get .Values.github.privateKeyPath | sha256sum }}
data:
  github-app.pem: {{ .Files.Get .Values.github.privateKeyPath | b64enc }}
