apiVersion: v1
kind: Service
metadata:
  name: {{ include "werft.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "werft.name" . }}
    helm.sh/chart: {{ include "werft.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ui.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.grpc }}
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "werft.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
