packages:
- name: dist
  type: typescript
  srcs:
  - src/**/*
  - public/**/*
  - package.json
  - .eslintignore
  - .env
  config:
    packaging: archive
    commands:
      build: ["yarn", "build"]
- name: rice
  type: generic
  deps:
  - :dist
  config:
    commands:
    - ["go", "get", "github.com/GeertJohan/go.rice/rice"]
    - ["mkdir", "pkg"]
    - ["mv", "pkg-webui--dist/build", "pkg/webui"]
    - ["sh", "-c", "echo cGFja2FnZSB3ZWJ1aQoKaW1wb3J0IHJpY2UgImdpdGh1Yi5jb20vR2VlcnRKb2hhbi9nby5yaWNlIgoKZnVuYyBmb28oKSB7CglyaWNlLkZpbmRCb3goInBrZy93ZWJ1aSIpCn0K | base64 --decode > index.go"]
    - ["sh", "-c", "$GOPATH/bin/rice embed-go"]
    - ["rm", "-rf", "pkg-webui--dist", "pkg", "index.go"]
    - ["go", "fmt", "./..."]